---
AWSTemplateFormatVersion: 2010-09-09

Description: EventBridge POC

Parameters:

  EnvName:
    Type: String
    Description: The environment name
    Default: dev


Resources:

  # EventBridge ################################################################

  ApplicationEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub app-bus-${EnvName}

  InstigatorEventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub instigator-rule-${EnvName}
      ScheduleExpression: rate(1 minute)
      State: ENABLED
      Targets:
        - Arn: !GetAtt InstigatorLambda.Arn
          Id: !Sub instigator-rule-target-${EnvName}

  EventBusHandlerOneRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub event-bus-handler-one-rule-${EnvName}
      EventBusName: !Ref ApplicationEventBus
      EventPattern: { "detail": {  "type": [ "One" ] } }
      State: ENABLED
      Targets:
        - Arn: !GetAtt EventBusHandlerOneLambda.Arn
          Id: !Sub event-bus-handler-one-rule-target-${EnvName}

  EventBusHandlerTwoRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub event-bus-handler-two-rule-${EnvName}
      EventBusName: !Ref ApplicationEventBus
      EventPattern: { "detail": {  "type": [ "Two" ] } }
      State: ENABLED
      Targets:
        - Arn: !GetAtt EventBusHandlerTwoLambda.Arn
          Id: !Sub event-bus-handler-two-rule-target-${EnvName}

  EventBusHandlerThreeRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub event-bus-handler-three-rule-${EnvName}
      EventBusName: !Ref ApplicationEventBus
      EventPattern: { "detail": {  "type": [ "Three" ] } }
      State: ENABLED
      Targets:
        - Arn: !GetAtt EventBusHandlerThreeLambda.Arn
          Id: !Sub event-bus-handler-three-rule-target-${EnvName}

  # EventBusHandlerOne #########################################################

  EventBusHandlerOneLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt EventBusHandlerOneLambda.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt EventBusHandlerOneRule.Arn

  EventBusHandlerOneLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub event-bus-handler-one-${EnvName}
      Code:
        ZipFile: |
          import json, boto3, os, random
          events = [ 'One', 'Two', 'Three' ]
          client = boto3.client('events')
          def handler(event, context):
            history = event['detail']['eventHistory']
            print(history)
            if len(history) >= int(os.environ['MAX_HOPS']):
              return 0
            history.append(os.environ['NAME'])
            payload = {
              'Source': context.invoked_function_arn,
              'DetailType': os.environ['NAME'],
              'Detail': json.dumps({
                'type': events[random.randint(0, 2)],
                'eventHistory': history
                }),
              'EventBusName': os.environ['BUS_ARN']
            }
            return client.put_events(Entries=[payload])
      Environment:
        Variables:
          BUS_ARN: !GetAtt ApplicationEventBus.Arn
          NAME: One
          MAX_HOPS: 3
      Handler: index.handler
      MemorySize: 128
      Role: !GetAtt EventBusHandlerLambdaIamRole.Arn
      Runtime: python3.8
      Timeout: 60

  # EventBusHandlerTwo #########################################################

  EventBusHandlerTwoLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt EventBusHandlerTwoLambda.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt EventBusHandlerTwoRule.Arn

  EventBusHandlerTwoLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub event-bus-handler-two-${EnvName}
      Code:
        ZipFile: |
          import json, boto3, os, random
          events = [ 'One', 'Two', 'Three' ]
          client = boto3.client('events')
          def handler(event, context):
            history = event['detail']['eventHistory']
            print(history)
            if len(history) >= int(os.environ['MAX_HOPS']):
              return 0
            history.append(os.environ['NAME'])
            payload = {
              'Source': context.invoked_function_arn,
              'DetailType': os.environ['NAME'],
              'Detail': json.dumps({
                'type': events[random.randint(0, 2)],
                'eventHistory': history
                }),
              'EventBusName': os.environ['BUS_ARN']
            }
            return client.put_events(Entries=[payload])
      Environment:
        Variables:
          BUS_ARN: !GetAtt ApplicationEventBus.Arn
          NAME: Two
          MAX_HOPS: 3
      Handler: index.handler
      MemorySize: 128
      Role: !GetAtt EventBusHandlerLambdaIamRole.Arn
      Runtime: python3.8
      Timeout: 60

  # EventBusHandlerThree #######################################################

  EventBusHandlerThreeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt EventBusHandlerThreeLambda.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt EventBusHandlerThreeRule.Arn

  EventBusHandlerThreeLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub event-bus-handler-three-${EnvName}
      Code:
        ZipFile: |
          import json, boto3, os, random
          events = [ 'One', 'Two', 'Three' ]
          client = boto3.client('events')
          def handler(event, context):
            history = event['detail']['eventHistory']
            print(history)
            if len(history) >= int(os.environ['MAX_HOPS']):
              return 0
            history.append(os.environ['NAME'])
            payload = {
              'Source': context.invoked_function_arn,
              'DetailType': os.environ['NAME'],
              'Detail': json.dumps({
                'type': events[random.randint(0, 2)],
                'eventHistory': history
                }),
              'EventBusName': os.environ['BUS_ARN']
            }
            return client.put_events(Entries=[payload])
      Environment:
        Variables:
          BUS_ARN: !GetAtt ApplicationEventBus.Arn
          NAME: Three
          MAX_HOPS: 3
      Handler: index.handler
      MemorySize: 128
      Role: !GetAtt EventBusHandlerLambdaIamRole.Arn
      Runtime: python3.8
      Timeout: 60

  # InstigatorLambda ###########################################################

  InstigatorEventBridgeRuleLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt InstigatorLambda.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt InstigatorEventBridgeRule.Arn

  InstigatorLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub instigator-${EnvName}
      Code:
        ZipFile: |
          import json, boto3, os, random
          client = boto3.client('events')
          events = [ 'One', 'Two', 'Three' ]
          def handler(event, context):
            payload = {
              'Source': context.invoked_function_arn,
              'DetailType': 'Instigator',
              'Detail': json.dumps({
                'type': events[random.randint(0, 2)],
                  'eventHistory': []
                }),
              'EventBusName': os.environ['BUS_ARN']
            }
            return client.put_events(Entries=[payload])
      Environment:
        Variables:
          BUS_ARN: !GetAtt ApplicationEventBus.Arn
      Handler: index.handler
      MemorySize: 128
      Role: !GetAtt InstigatorLambdaIamRole.Arn
      Runtime: python3.8
      Timeout: 60

  # IAM ########################################################################

  EventBusHandlerLambdaIamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub event-bus-handler-lambda-${EnvName}
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref ApplicationEventBusPutIamPolicy
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
        - Key: EnvName
          Value: !Ref EnvName

  InstigatorLambdaIamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub instigator-lambda-${EnvName}
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref ApplicationEventBusPutIamPolicy
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
        - Key: EnvName
          Value: !Ref EnvName

  ApplicationEventBusPutIamPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub app-eventbus-put-events-${EnvName}
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Resource: !GetAtt ApplicationEventBus.Arn
            Effect: Allow
            Action: events:PutEvents


Outputs:

  ApplicationEventBusName:
    Value: !Ref ApplicationEventBus
    Export:
      Name: !Sub ${AWS::StackName}-ApplicationEventBusName

  ApplicationEventBusArn:
    Value: !GetAtt ApplicationEventBus.Arn
    Export:
      Name: !Sub ${AWS::StackName}-ApplicationEventBusArn

  InstigatorEventBridgeRuleArn:
    Value: !GetAtt InstigatorEventBridgeRule.Arn
    Export:
      Name: !Sub ${AWS::StackName}-InstigatorEventBridgeRuleArn

  ApplicationEventBusPutIamPolicyArn:
    Value: !Ref ApplicationEventBusPutIamPolicy
    Export:
      Name: !Sub ${AWS::StackName}-ApplicationEventBusPutIamPolicyArn




